version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes_from:
      - data
  rails: &app_base
    build: 
      context: .
      dockerfile: dockerfile-dev
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/myapp
    volumes_from:
      - data
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mysql
      MYSQL_HOST: db
    tty: true
    stdin_open: true
  spring:
    <<: *app_base
    command: bundle exec spring server
    ports: []
    tty: false
    stdin_open: false
  data:
    image: busybox
    volumes:
      - datavol:/var/lib/mysql
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
volumes:
  datavol:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
